<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

<!--        <!-- Le styles -->
<!--        --><?php //echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        echo $this->headLink()->prependStylesheet($this->basePath('css/style.css'));
//                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>
<!---->
<!--        <!-- Scripts -->
<!--        --><?php //echo $this->headScript()
//            ->prependFile($this->basePath('js/bootstrap.min.js'))
//            ->prependFile($this->basePath('js/jquery.min.js'))
//            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
//        ; ?>

            <!-- Required meta tags -->
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    </head>
    <body style="background-color: #eff2f1">
<!--        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">-->
<!--            <div class="container">-->
<!--                <div class="navbar-header">-->
<!--                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">-->
<!--                        <span class="icon-bar"></span>-->
<!--                        <span class="icon-bar"></span>-->
<!--                        <span class="icon-bar"></span>-->
<!--                    </button>-->
<!--                    <a class="navbar-brand" href="--><?php //echo $this->url('home') ?><!--"><img src="--><?php //echo $this->basePath('img/zf2-logo.png') ?><!--" alt="Zend Framework 2"/>&nbsp;--><?php //echo $this->translate('Skeleton Application') ?><!--</a>-->
<!--                </div>-->
<!--                <div class="collapse navbar-collapse">-->
<!--                    <ul class="nav navbar-nav">-->
<!--                        <li class="active"><a href="--><?php //echo $this->url('home') ?><!--">--><?php //echo $this->translate('Home') ?><!--</a></li>-->
<!--                    </ul>-->
<!--                </div><!--/.nav-collapse -->
<!--            </div>-->
<!--        </nav> -->
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p><?php echo date('Y') ?> by Kyle Andrews</p>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
