<?php
//    $this->headScript()->appendFile($this->basePath('js/Application/index/adminReport.js'));
?>
<script src="../../../../../public/js/Application/index/adminReport.js" type="application/javascript"></script>
<link link href="../../../../../public/css/Application/index/adminReport.css" rel="stylesheet" type="text/css" media="all"/>
<div class="row">
    <div class="col-xs-12">
        <h1>
            Admin Report<br><br>
        </h1>
    </div>
</div>
<div class="row">
    <div class="loader"></div>
</div>
<div class="row d-none" id="tableReportContainer">
    <div class="table-responsive">
        <table class="table" id="adminReport">
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Address 1
                </th>
                <th>
                    Address 2
                </th>
                <th>
                    City
                </th>
                <th>
                    State
                </th>
                <th>
                    Zip
                </th>
                <th>
                    Country
                </th>
                <th>
                    Created
                </th>
            </tr>
            <tbody>
            </tbody>
        </table>
    </div>
</div>