<?php
    echo $this->headScript()->appendFile($this->basePath('js/Application/index/adminReport.js'));
    echo $this->headLink()->appendStylesheet($this->basePath('css/Application/index/adminReport.css'));
?>
<div class="row">
    <div class="col-sm-12">
        <h1 class="title">
            Admin Report
        </h1>
    </div>
</div>
<div class="row">
    <div class="loader"></div>
</div>
<div class="row d-none" id="tableReportContainer">
    <div class="table-responsive">
        <table class="table" id="adminReport">
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Address 1
                </th>
                <th>
                    Address 2
                </th>
                <th>
                    City
                </th>
                <th>
                    State
                </th>
                <th>
                    Zip
                </th>
                <th>
                    Country
                </th>
                <th>
                    Created
                </th>
            </tr>
            <tbody>
            </tbody>
        </table>
    </div>
</div>